#!/usr/bin/env python3
"""
FPG — Synonym Generator (Layer 2)
Reads all language JSON files, extracts English dictionary keys,
then uses NLTK WordNet to find synonyms for each key.
Outputs js/synonyms.js with a comprehensive synonym map.

Usage:
    pip install nltk
    python3 scripts/generate_synonyms.py
    (NLTK will prompt to download 'wordnet' on first run)
"""

import json, os, re, sys
from pathlib import Path

try:
    import nltk
    from nltk.corpus import wordnet as wn
except ImportError:
    print("ERROR: nltk not installed. Run: pip install nltk")
    sys.exit(1)

# Download wordnet data if needed
try:
    wn.synsets("test")
except LookupError:
    print("Downloading NLTK WordNet data...")
    nltk.download("wordnet")
    nltk.download("omw-1.4")

LANGUAGES_DIR = Path(__file__).parent.parent.parent.parent / "languages"
OUTPUT_FILE = Path(__file__).parent.parent / "js" / "synonyms.js"

def load_all_keys():
    keys = set()
    for fname in LANGUAGES_DIR.glob("*.json"):
        try:
            d = json.loads(fname.read_text())
            entries = d.get("entries", {})
            for k in entries:
                # Only single words (no spaces, reasonable length)
                if " " not in k and len(k) >= 3 and re.match(r'^[a-zA-Z\-]+$', k):
                    keys.add(k.lower())
        except Exception as e:
            print(f"Warning: could not read {fname}: {e}")
    return keys

def get_synonyms(word):
    """Get all WordNet synonyms for a word across all POS."""
    synonyms = set()
    for synset in wn.synsets(word):
        for lemma in synset.lemmas():
            name = lemma.name().replace("_", " ").lower()
            if name != word and len(name) >= 2:
                synonyms.add(name)
        # Also include hypernyms (broader terms) and hyponyms (narrower)
        for hypernym in synset.hypernyms():
            for lemma in hypernym.lemmas():
                name = lemma.name().replace("_", " ").lower()
                if name != word:
                    synonyms.add(name)
    return synonyms

def build_groups(keys):
    """Build synonym groups from WordNet, seeded by our dictionary keys."""
    # Map: canonical_key → set of synonyms
    key_synonyms = {}
    print(f"Processing {len(keys)} dictionary keys...")

    for i, key in enumerate(sorted(keys)):
        if i % 100 == 0:
            print(f"  {i}/{len(keys)}...")
        syns = get_synonyms(key)
        if syns:
            key_synonyms[key] = syns

    # Build groups: merge keys that share synonyms
    # Simple approach: each key + its synonyms is one group
    groups = []
    seen = set()

    for key, syns in key_synonyms.items():
        if key in seen:
            continue
        group = {key} | {s for s in syns if len(s.split()) == 1}  # single-word only
        group = sorted(group)
        if len(group) >= 2:
            groups.append(group)
            seen.update(group)

    return groups

def write_output(groups):
    header = '''/* =============================================
   FPG — Layer 2: Semantic Synonym Expansion
   AUTO-GENERATED by scripts/generate_synonyms.py
   Do not hand-edit; re-run the script to regenerate.
   ============================================= */

window.FPG_Synonyms = (function () {
    "use strict";

    const GROUPS = [
'''
    footer = '''    ];

    const wordToGroup = new Map();
    GROUPS.forEach((group, idx) => {
        group.forEach(word => {
            if (!wordToGroup.has(word)) wordToGroup.set(word, []);
            wordToGroup.get(word).push(idx);
        });
    });

    function findMatch(word, dictKeys) {
        const lower = word.toLowerCase();
        const groupIndices = wordToGroup.get(lower);
        if (!groupIndices) return null;
        for (const idx of groupIndices) {
            for (const groupWord of GROUPS[idx]) {
                if (groupWord !== lower && (dictKeys instanceof Set ? dictKeys.has(groupWord) : groupWord in dictKeys)) {
                    return groupWord;
                }
            }
        }
        return null;
    }

    function getSynonyms(word) {
        const lower = word.toLowerCase();
        const groupIndices = wordToGroup.get(lower);
        if (!groupIndices) return [];
        const result = new Set();
        for (const idx of groupIndices) {
            GROUPS[idx].forEach(w => { if (w !== lower) result.add(w); });
        }
        return [...result];
    }

    return { findMatch, getSynonyms, GROUPS };
})();
'''
    lines = []
    for group in groups:
        # Escape for JS string
        escaped = [w.replace("\\", "\\\\").replace('"', '\\"') for w in group]
        lines.append('        ["' + '", "'.join(escaped) + '"],')

    content = header + "\n".join(lines) + "\n" + footer
    OUTPUT_FILE.write_text(content)
    print(f"\nWrote {len(groups)} synonym groups to {OUTPUT_FILE}")

def main():
    keys = load_all_keys()
    print(f"Found {len(keys)} unique single-word dictionary keys")
    groups = build_groups(keys)
    write_output(groups)
    print("Done. Run this script again after adding new language files.")

if __name__ == "__main__":
    main()
